---
galaxy_release_number: '19.05'
galaxy_version: "release_19.05"
galaxy_root_dir: "/root/galaxy-prod"
galaxy_common_dir: "/root/galaxy-common"
galaxy_config_dir: "/root/galaxy-prod/config"
galaxy_real_dir: "/root/galaxy-19.05"
galaxy_user: "root"
galaxy_user_group: "root"
galaxy_create_user: false
galaxy_server_dir: "/root/galaxy-prod/server"
report_configs: "root"
galaxy_database_connection: "postgresql://postgres:postgres@localhost:5432/root"
galaxy_install_database_connection: "postgresql://postgres:postgres@localhost:5432/root"
galaxy_venv_dir: "/root/galaxy-prod/venv"
supervisor_configs: "galaxy-supervisor"
supervisord_conf_dir: "/etc/supervisord.d"
proftpd_configs: "galaxy"
remote_user: "galaxy"
server_name: "galaxy.ca"
galaxy_admin_users: "username,admin@localhost.com"
galaxy_require_login: false
galaxy_allow_user_creation: true
galaxy_allow_user_impersonation: true
galaxy_ftp_dir: "/tmp/Galaxies/ftp/unknown"
install_tools: false
galaxy_tool_list: "%{lookup('tools::tool_list')}"
galaxy_jupyter_address: "galaxy-docker.canada.ca"
galaxy_jupyter_port: "2375"
galaxy_infrastructure_url: "galaxy.ca"
dev_env: true
galaxy_waffleiron_url: http://websiteiron.com
import_irida: false
create_irida_user: false
irida_user_username: 'username'
irida_user_password: 'password'
irida_user_key: 'key'
irida_client_id_config: 'id'
irida_client_secret: 'password'
galaxy_api_key: 'thisisaweakandunencryptedkey!'
create_db: true
galaxy_tmp_dir: '/tmp'
ldap_enable: false
ldap_server: ''
ldap_search_user: ''
ldap_search_password: ''
ldap_search_base: ""
ldap_domain: ''
