---
- name: Prepare Linux Enviroment
  hosts: galaxyservers
  become: yes
  roles:
    - geerlingguy.repo-epel
    - geerlingguy.git
    - geerlingguy.pip
    - jimbydamonk.libselinux-python
  tasks:
    - name: Install required system packages
      yum:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
          - ant
          - cmake
          - curl
          - gcc-c++
          - gcc
          - gcc-gfortran
          - libffi-devel
          - lapack-devel
          - ncurses-devel
          - openblas-devel
          - pam-devel
          - make
          - mercurial
          - openssh-server
          - patch
          - perl
          - pkgconfig
          - python-devel
          - python-boto
          - python-prettytable
          - python-psycopg2
          - python-virtualenv
          - rsync
          - samtools
          - sudo
          - swig
          - sysstat
          - unzip
          - wget
          - zlib-devel
          - libsemanage-python
          - kernel-devel

    - name: Install packages for system maintenance
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - atop
          - ipython
          - iotop
          - htop
          - iftop
          - nmon
          - axel
          - vim

  post_tasks:
    - name: Change SELinux status
      selinux:
          state: disabled
          
    - name: Set SELinux in permissive mode until the machine is rebooted
      command: setenforce 0

    - name: Set timezone to PST
      become: yes
      timezone:
        name: America/Vancouver
        
    - name: Remove policycoreutils
      yum:
          name: policycoreutils-python
          state: absent
    - name: Install policycoreutils
      yum:
          name: policycoreutils-python
          state: latest