- name: Prepare Linux Enviroment
  hosts: galaxyservers
  become: yes
  roles:
    - geerlingguy.repo-epel
    - geerlingguy.git
    - geerlingguy.pip
    - jimbydamonk.libselinux-python
  tasks:
    - include: centos-prep.yml
    
- hosts: galaxyservers
  become: yes
  handlers:
    - name: Restart Galaxy
      supervisorctl:
        name: galaxy
        state: restarted
  roles:
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - galaxyproject.galaxy
    - uchida.miniconda
    - usegalaxy-eu.supervisor
    - galaxyproject.nginx
  tasks:
    - name: Install uWSGI
      pip:
        name: uWSGI
        virtualenv: "{{ galaxy_venv_dir }}"

    - name: Import Toolsheds
      copy:
        src: files/tool_sheds_conf.xml
        dest: "{{galaxy_server_dir}}/config"
      notify: Restart Galaxy

- name: Setup Tools
  hosts: galaxyservers
  gather_facts: false
  become: yes
  roles:
   - galaxyproject.galaxy-tools

  #- vidtd
  #- galaxyproject.proftpd

# - name: Install Dependecies for Interactive Environments 
#   hosts: galaxyservers
#   tasks:
#     - include: roles/galaxyproject.interactive_environments/tasks/install_dependencies.yml
#   post_tasks:
#   - name: Install pre-gyp with NPM
#     npm:
#       name: node-pre-gyp
#       global: yes

# - name: setup local environment
#   hosts: galaxyservers
#   roles:
#    - galaxyproject.interactive_environments
