- hosts: galaxyservers
  become: yes
  handlers:
    - name: Restart Galaxy
      supervisorctl:
        name: galaxy
        state: restarted
  roles:
    - galaxyproject.galaxy
    - uchida.miniconda
    - usegalaxy-eu.supervisor
    - vidtd
  tasks:
    - name: Install uWSGI
      pip:
        name: uWSGI
        virtualenv: "{{ galaxy_venv_dir }}"

    - name: Import Toolsheds
      copy:
        src: files/tool_sheds_conf.xml
        dest: "{{galaxy_server_dir}}/config"
      notify: Restart Galaxy