# Refernce: https://galaxyproject.github.io/training-material/topics/admin/tutorials/ansible-galaxy/tutorial.html
- hosts: galaxyservers
  become: yes
  pre_tasks:
    - name: Set timezone to PST
      become: yes
      timezone:
        name: America/Vancouver

    - name: Install packages
      package:
        name: ['python-psycopg2', 'git', 'python-virtualenv', 'make']

  handlers: 
    - name: Restart Galaxy
      supervisorctl:
        name: galaxy
        state: restarted
  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - galaxyproject.galaxy
    - uchida.miniconda
    - usegalaxy-eu.supervisor
    - galaxyproject.nginx
    #- galaxyproject.proftpd
    #- vidtd
  post_tasks:
    - name: Install uwsgidecorators
      pip:
        name: uwsgidecorators
        virtualenv: "{{ galaxy_venv_dir }}"

# - name: Setup Toolshed
#   hosts: galaxyservers
#   gather_facts: False
#   connection: local
#   roles:
#    - galaxyproject.galaxy-tools

# - name: Install Dependecies for Interactive Environments 
#   hosts: galaxyservers
#   tasks:
#     - include: roles/galaxyproject.interactive_environments/tasks/install_dependencies.yml

# - name: setup local environment
#   hosts: galaxyservers
#   gather_facts: False
#   connection: local
#   roles:
#    - galaxyproject.interactive_environments
