- name: Prepare Linux Enviroment
  hosts: galaxyservers
  become: yes
  roles:
    - role: geerlingguy.repo-epel
      when: sys_prep == true
    - role: geerlingguy.git
      when: sys_prep == true
    - role: geerlingguy.pip
      when: sys_prep == true
    - role: jimbydamonk.libselinux-python
      when: sys_prep == true
  tasks:
    - include: centos-prep.yml
      when: sys_prep == true
    
- hosts: galaxyservers
  become: yes
  handlers:
    - name: Restart Galaxy
      supervisorctl:
        name: galaxy
        state: restarted
  roles:
    - role: galaxyproject.postgresql
      when: create_db == true
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
      when: create_db == true
    - galaxyproject.galaxy
    - role: uchida.miniconda
      when: install_miniconda == true
    - role: usegalaxy-eu.supervisor
      when: install_supervisor == true
    - role: galaxyproject.nginx
      when: install_nginx == true
  tasks:
    - name: Install uWSGI
      pip:
        name: uWSGI
        virtualenv: "{{ galaxy_venv_dir }}"

    - name: Import Toolsheds
      copy:
        src: files/tool_sheds_conf.xml
        dest: "{{galaxy_server_dir}}/config"
      notify: Restart Galaxy

- name: Setup Tools
  hosts: galaxyservers
  gather_facts: false
  become: yes
  roles:
   - galaxyproject.galaxy-tools

  #- vidtd
  #- galaxyproject.proftpd

# - name: Install Dependecies for Interactive Environments 
#   hosts: galaxyservers
#   tasks:
#     - include: roles/galaxyproject.interactive_environments/tasks/install_dependencies.yml
#   post_tasks:
#   - name: Install pre-gyp with NPM
#     npm:
#       name: node-pre-gyp
#       global: yes

# - name: setup local environment
#   hosts: galaxyservers
#   roles:
#    - galaxyproject.interactive_environments
