#https://biohpc.blogspot.com/2016/10/sge-installation-of-son-of-grid-engine.html
- name: Install SGE
  hosts: galaxyservers
  become: yes
  pre_tasks:
    - name: Creates directory for SGE
      file:
        path: "{{sge_root_dir}}"
        state: directory
    - name: Install required system packages
      yum:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
          - jemalloc-devel
          - openssl-devel
          - ncurses-devel
          - libXmu-devel
          - hwloc-devel
          - hwloc hwloc-libs
          - java-devel
          - javacc
          - ant-junit
          - libdb-devel
          - db4-utils
          - perl-XML-Simple
          - perl-Env
    - name: Ensure group sgeadmin exists
      group:
        name: sgeadmin
        gid: 490
        state: present
    - name: Add the user 'sgeadmin' with a bash shell, add sgeadmin to sgeadmin group
      user:
        name: sgeadmin
        uid: 495
        shell: /bin/bash
        groups: sgeadmin,sudo
        comment: "SGE Admin"
        create_home: yes
        append: yes
        system: yes
    - name: Make sure group sgeadmin is in the sudoers configuration
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sgeadmin'
        line: '%sgeadmin ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s
  tasks:
    - name: Download SGE from Source
      get_url: 
        url: https://arc.liv.ac.uk/downloads/SGE/releases/8.1.9/sge-8.1.9.tar.gz
        dest: "{{sge_root_dir}}"
    - name: Extract SGE tar file
      unarchive:
        src: "{{sge_root_dir}}/sge-8.1.9.tar.gz"
        dest: "{{sge_root_dir}}"
        extra_opts:
          - --verbose
          - --preserve-permissions
    - name: Run bootstrap scripts to install SGE
      shell: sh scripts/bootstrap.sh && ./aimk && ./aimk -man
      args:
        chdir: "{{sge_root_dir}}/sge-8.1.9/source/"