- name: Install dependencies
  hosts: galaxyservers
  remote_user: vagrant
  become: yes
  pre_tasks:
    - name: Install EPEL repo
      yum:
        pkg: "epel-release"
        update_cache: yes
        state: present

    - name: Install libselinux
      yum:
        pkg: "libselinux-python"
        update_cache: yes
        state: present

    - name: Install packages
      yum:
        pkg: [python-psycopg2, git, python-virtualenv, python-pip, make]
        update_cache: yes
        state: present

- name: Install and configure Galaxy
  hosts: galaxyservers
  become: yes
  roles:
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: yes
      become_user: postgres
    - galaxyproject.galaxy
    - galaxyproject.nginx
    - miniconda
  post_tasks:
    - name: Install uwsgidecorators
      pip:
        name: uwsgidecorators
        virtualenv: "{{ galaxy_venv_dir }}"
  handlers:
    - name: Restart Galaxy
      supervisorctl:
        name: galaxy
        state: restarted

- name: Install and configure supervisor
  hosts: galaxyservers
  become: yes
  roles:
    - supervisor

- name: Install and configure ProFTPD
  hosts: galaxyservers
  become: yes
  roles:
    - proftpd

- name: setup toolshed
  hosts: localhost
  gather_facts: False
  connection: local
  roles:
   - galaxyproject.galaxy-tools

- hosts: galaxyservers
  tasks:
      - include: roles/galaxyproject.interactive_environments/tasks/install_dependencies.yml
- name: setup local environment
  hosts: localhost
  gather_facts: False
  connection: local
  roles:
   - galaxyproject.interactive_environments
