- name: Install dependencies
  hosts: galaxyservers
  remote_user: vagrant
  become: yes
  pre_tasks:
    - name: Set timezone to PST
      become: yes
      become_user: root
      timezone:
        name: America/Vancouver

    - name: Install EPEL repo
      yum:
        pkg: "epel-release"
        update_cache: yes
        state: present

    - name: Install packages
      yum:
        pkg: [libselinux-python,python-psycopg2, git, python-virtualenv, python-pip, make]
        update_cache: yes
        state: present

- name: Install and configure Galaxy
  hosts: galaxyservers
  become: yes
  roles:
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: yes
      become_user: postgres
    - galaxyproject.galaxy
    - usegalaxy-eu.certbot
    - galaxyproject.nginx
    - uchida.miniconda 
  post_tasks:
    - name: Install uwsgidecorators
      pip:
        name: uwsgidecorators
        virtualenv: "{{ galaxy_venv_dir }}"
  handlers:
    - name: Restart Galaxy
      supervisorctl:
        name: galaxy
        state: restarted

- name: Install and configure supervisor
  hosts: galaxyservers
  become: yes
  roles:
    - usegalaxy-eu.supervisor

- name: Install and configure ProFTPD
  hosts: galaxyservers
  become: yes
  roles:
    - galaxyproject.proftpd

- name: setup toolshed
  hosts: localhost
  gather_facts: False
  connection: local
  roles:
   - galaxyproject.galaxy-tools

- hosts: galaxyservers
  tasks:
      - include: roles/galaxyproject.interactive_environments/tasks/install_dependencies.yml
- name: setup local environment
  hosts: localhost
  gather_facts: False
  connection: local
  roles:
   - galaxyproject.interactive_environments
