---
- name: galaxyproject.galaxy
  src: galaxyproject.galaxy
  #version: 0.8.4

- name: galaxyproject.galaxy-tools
  src: galaxyproject.galaxy-tools

- name: galaxyproject.interactive_environments
  src: galaxyproject.interactive_environments

- name: galaxyproject.nginx
  src: galaxyproject.nginx
  version: 0.6.2

- name: galaxyproject.postgresql
  src: galaxyproject.postgresql
  #version: 1.0.1

- name: galaxyproject.proftpd
  src: galaxyproject.proftpd

- name: natefoo.postgresql_objects
  src: natefoo.postgresql_objects
  #version: 1.1

- name: grycap.sge
  src: grycap.sge

- name: uchida.miniconda 
  src: uchida.miniconda
  #version: 0.3.0

- name: geerlingguy.repo-epel
  src: geerlingguy.repo-epel

- name: geerlingguy.pip
  src: geerlingguy.pip

- name: geerlingguy.git
  src: geerlingguy.git

- name: jimbydamonk.libselinux-python
  src: jimbydamonk.libselinux-python

- name: usegalaxy-eu.supervisor
  src: https://github.com/usegalaxy-eu/ansible-role-supervisor
  #version: 2.0.2

- name: usegalaxy-eu.certbot
  src: https://github.com/usegalaxy-eu/ansible-certbot

