---
- name: galaxyproject.galaxy
  src: https://github.com/galaxyproject/ansible-galaxy

- name: galaxyproject.galaxy-tools
  src: https://github.com/galaxyproject/ansible-galaxy-tools

- name: galaxyproject.interactive_environments
  src: https://github.com/galaxyproject/ansible-interactive-environments

- name: galaxyproject.nginx
  src: https://github.com/galaxyproject/ansible-nginx

- name: galaxyproject.postgresql
  src: https://github.com/galaxyproject/ansible-postgresql

- name: galaxyproject.proftpd
  src: https://github.com/galaxyproject/ansible-proftpd

- name: natefoo.postgresql_objects
  src: https://github.com/natefoo/ansible-postgresql-objects

- name: usegalaxy-eu.supervisor
  src: https://github.com/usegalaxy-eu/ansible-role-supervisor

- name: usegalaxy-eu.certbot
  src: https://github.com/usegalaxy-eu/ansible-certbot

- name: uchida.miniconda 
  src: https://github.com/uchida/ansible-miniconda-role