- name: install supervisor
  yum:
    name: supervisor
    update_cache: yes
    state: present

- name: make /etc/supervisor.d directory
  file:
    path: "/etc/supervisord.d"
    state: directory
    group: root
    owner: root

- name: make /var/run/supervisor directory
  file:
    path: "/var/run/supervisor"
    state: directory

- name: Install supervisord configs
  template:
    src: "templates/supervisord.conf"
    dest: "/etc/supervisord.conf"

- name: create supervisor log directory
  file:
    path: /var/log/supervisor
    state: directory

- name: reload systemctl configs
  command: systemctl daemon-reload

- name: Ensure supervisor is running
  service:
    name: supervisord
    enabled: yes
    state: started

- name: change ownership of supervisor
  become: yes
  become_user: root
  file:
   path: "/var/run/supervisor"
   state: directory
   owner: "{{galaxy_user}}"
   group: "{{galaxy_user_group}}"

- name: update supervisor
  command: /usr/bin/supervisorctl update
  ignore_errors: yes
