---

- name: Create/invoke script virtualenv
  become: yes
  become_user: "{{ galaxy_user }}"
  pip:
    # Pinned version should make sure ephemeris version matches what the role has been tested with
    name: ['ephemeris==0.4.0','pyyaml','bioblend','drmaa']
    virtualenv: "{{ galaxy_tools_base_dir }}/venv"
    virtualenv_command: "{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
- include: install_tool_list.yml
  with_items: '{{ galaxy_tools_tool_list_files }}'
  loop_control:
    loop_var: tool_list_file
