- name: copy cleanup.sh
  become: yes
  become_user: "{{ galaxy_user }}"
  template:
    dest: "{{ galaxy_root_dir }}/cleanup.sh"
    owner: "{{ galaxy_user }}"
    group: "{{ galaxy_user_group }}"
    src: cleanup.sh.j2
    
- name: add cleanup.sh crontab job
  become: yes
  become_user: root
  lineinfile:
    group: "{{ galaxy_user_group }}"
    owner: "{{ galaxy_user }}"
    path: "/var/spool/cron/{{ galaxy_user }}"
    state: present
    create: yes
    line: "00 00 * * * {{galaxy_root_dir }}/cleanup.sh"
    
- name: add database/tmp deletion crontab job
  become: yes
  become_user: root
  lineinfile:
    group: "{{ galaxy_user_group }}"
    owner: "{{ galaxy_user }}"
    path: "/var/spool/cron/{{ galaxy_user }}"
    state: present
    create: yes
    line: '00 00 * * * find {{ galaxy_server_dir }}/database/tmp -type d -mtime +30 -exec rm -r \"{}\" \;'

- name: add jobs deletion crontab job
  become: yes
  become_user: root
  lineinfile:
    group: "{{ galaxy_user_group }}"
    owner: "{{ galaxy_user }}"
    path: "/var/spool/cron/{{ galaxy_user }}"
    state: present
    create: yes
    line: '00 00 * * * find {{ galaxy_server_dir }}/database/jobs -maxdepth 3 -mindepth 3 -type d -mtime +30 -exec rm -r \"{}\" \;'
