---
# Manage Galaxy framework dependencies

- include: virtualenv.yml

# virtualenv_command is still required if `virtualenv` isn't on $PATH, even if the venv already exists.
- name: Install Galaxy base dependencies
  pip:
    requirements: "{{ galaxy_requirements_file }}"
    extra_args: "--extra-index-url https://wheels.galaxyproject.org/"
    virtualenv: "{{ galaxy_venv_dir }}"
    virtualenv_command: "{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
  environment:
    PYTHONPATH: null
    VIRTUAL_ENV: "{{ galaxy_venv_dir }}"

- name: Collect Galaxy conditional dependency requirement strings
  command: "{{ galaxy_venv_dir }}/bin/python -c \"import galaxy.dependencies; print '\\n'.join(galaxy.dependencies.optional('{{ galaxy_config_file }}'))\""
  environment:
    PYTHONPATH: "{{ galaxy_server_dir }}/lib"
  register: conditional_dependencies

- name: Install Galaxy conditional dependencies
  pip: 
    name: '{{ conditional_dependencies.stdout_lines }}'
    extra_args: "--index-url https://wheels.galaxyproject.org/simple/"
    virtualenv: "{{ galaxy_venv_dir }}"
    virtualenv_command: "{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
  environment:
    PYTHONPATH: null
    VIRTUAL_ENV: "{{ galaxy_venv_dir }}"

- name: Install javascript dependencies libraries if they have not been compiled
  command: "{{ galaxy_server_dir }}/scripts/common_startup.sh"
  args:
    chdir: "{{ galaxy_server_dir }}"
    creates: "{{ galaxy_server_dir }}/static/scripts/"
