---
# Instantiate mutable config files

- name: Create mutable configuration file directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ galaxy_mutable_config_dir }}"
    - "{{ galaxy_tool_dependency_dir }}"

- name: Instantiate mutable configuration files
  command: cp {{ item.src }} {{ item.dest }}
  args:
    creates: "{{ item.dest }}"
  with_items: "{{ galaxy_mutable_configs }}"

#- name: Add tool_destinations_sample
 # copy:
  # src: files/tool_destinations.yml.sample
  # dest: "{{ galaxy_server_dir }}/config/tool_destinations.yml.sample"

#- name: Add tool_sheds_conf
#  copy:
#   src: files/tool_sheds_conf.xml
 #  dest: "{{ galaxy_root_dir }}/config/tool_sheds_conf.xml"
   #path: "{{ galaxy_root_dir }}/config/tool_sheds_conf.xml"
 # with_items: files/tool_sheds_conf.xml
