- name: Copy user creation script
  become: yes
  become_user: "{{ galaxy_user }}"
  template:
    dest: "{{ galaxy_root_dir }}/create_galaxy_user.py"
    owner: "{{ galaxy_user }}"
    group: "{{ galaxy_user_group }}"
    src: create_galaxy_user.py.j2

- name: Run user creation script
  become: yes
  become_user: "{{ galaxy_user }}"
  command: bash -c 'source {{ galaxy_venv_dir }}/bin/activate && python ./create_galaxy_user.py --user={{ irida_user_username }} --password={{ irida_user_password }} --key={{ irida_user_key }} && touch irida_user_exists'
  args:
    chdir: "{{ galaxy_root_dir }}"
    creates: "{{ galaxy_root_dir }}/irida_user_exists"
