---
# tasks file for galaxyprojectdotorg.interactive_enviroments

- name: Set IE proxy restart handler name
  set_fact:
    interactive_environments_proxy_restart_handler: supervisorctl restart gie_proxy
  when: interactive_environments_supervisor_conf_dir is defined

- name: Set path variables if installing in place
  set_fact:
    interactive_environments_plugin_path: "{{ galaxy_server_dir ~ '/config/plugins/interactive_environments' }}"
    interactive_environments_proxy_path: "{{ galaxy_server_dir ~ '/lib/galaxy/web/proxy/js' }}"
  when: interactive_environments_install_method == 'inplace'

- name: Include tasks for synchronizing IE components
  include: synchronize_components.yml
  when: interactive_environments_install_method == 'copy'

- name: Install node-pre-gyp with NPM
  become: yes
  become_user: "{{galaxy_user}}"
  command: npm install node-pre-gyp -g

- name: Install proxy dependencies with NPM
  become: yes
  become_user: "{{galaxy_user}}"
  command: npm install --unsafe-perm
  args:
       chdir: "{{ interactive_environments_proxy_path }}"

- name: Create IE ini config files
  become: yes
  become_user: "{{galaxy_user}}"
  template:
    src: templates/config.ini.j2
    dest: "{{ galaxy_config_dir }}/plugins/interactive_environments/{{ item }}/config/{{ item }}.ini"
    backup: yes
  with_items: "{{ interactive_environments_config_files }}"

- name: Create rstudio allowed image files
  become: yes
  become_user: "{{galaxy_user}}"
  copy:
    src: files/rstudio-allowed_images.yml
    dest: "{{ galaxy_config_dir }}/plugins/interactive_environments/rstudio/config/allowed_images.yml"

- name: Include tasks for supervisor config
  include: supervisor.yml
  when: interactive_environments_supervisor_conf_dir is defined

- name: Include tasks for Docker SSL client
  include: docker_ssl.yml
  when: interactive_environments_ssl is defined

- name: Include tasks for nginx config
  include: webserver_conf.yml
  vars:
    interactive_environments_web_conf_dir: "{{ interactive_environments_nginx_conf_dir }}"
    interactive_environments_web_conf_templates: "{{ interactive_environments_nginx_conf_templates }}"
  when: interactive_environments_nginx_conf_dir is defined

- name: Include tasks for Apache config
  include: webserver_conf.yml
  vars:
    interactive_environments_web_conf_dir: "{{ interactive_environments_apache_conf_dir }}"
    interactive_environments_web_conf_templates: "{{ interactive_environments_apache_conf_templates }}"
  when: interactive_environments_apache_conf_dir is defined
